This commit was manufactured by cvs2git to create tag 'mysql-3_23_57-3'.
Sprout from RA-branch 2003-09-16 20:39:57 UTC cvs2git <feedback@pld-linux.org> 'This commit was manufactured by cvs2git to create branch 'RA-branch'.'
Cherrypick from unlabeled-1.24.2 2003-02-25 23:16:53 UTC kloczek <kloczek@pld-linux.org> '- removed double checking $MYSQLD_CONFIG,':
    mysql.init -> 1.24.2.1

diff --git a/mysql.init b/mysql.init
--- a/mysql.init
+++ b/mysql.init
@@ -14,29 +14,26 @@
 # Get network config
 . /etc/sysconfig/network
 
-# Check that networking is up
-if is_yes "${NETWORKING}"; then
-	if [ ! -f /var/lock/subsys/network -a "$1" != stop -a "$1" != status -a "$1" != init ]; then
-		msg_network_down MySQL
-		exit 1
-	fi
-else
-	exit 0
+# Check that networking is up.
+if is_no "${NETWORKING}"; then
+	msg_network_down MySQL
+	exit 1
 fi
 
 MYSQLD_ERRLOG=/var/log/mysql/err
 MYSQLD_CONFIG=/etc/mysqld.conf 
 
 # Get service config
-if [ -f /etc/sysconfig/mysql ]; then
+if [ -f /etc/sysconfig/mysql ] ; then
 	. /etc/sysconfig/mysql
 fi
 
-# Daemon doesn't die if config doesn't exist
+# Daemon don't dies if config doesn't exists
 if [ ! -f $MYSQLD_CONFIG ]; then 
-	nls "%s config %s does not exist." MySQL "$MYSQLD_CONFIG" >&2
-	exit 6
+	echo "MySQL config $MYSQLD_CONFIG not exists"
+	exit 1
 fi
+
 
 eval `awk '
 /^[ \t]*\[.*\][ \t]*$/ {
@@ -58,32 +55,34 @@ END {
 ' /etc/mysqld.conf`
 
 if [ -z $MYSQL_DATA_DIR ]; then 
-	echo "$(nls 'MySQL datadir %s not configured properly' "$MYSQL_DATA_DIR")"'!' >&2
-	nls "Edit %s and configure it." "$MYSQLD_CONFIG" >&2
-	exit 6
+	echo "MySQL datadir $MYSQL_DATA_DIR not configured propely!"
+	echo "Edit $MYSQLD_CONFIG and configure it."
+	exit 1
 fi
 
 if [ -z $MYSQL_USER ]; then 
-	echo "$(nls 'MySQL user not configured properly')"'!' >&2
-	nls "Edit %s and configure it." "$MYSQLD_CONFIG" >&2
-	exit 6
+	echo "MySQL user not configured propely!"
+	echo "Edit $MYSQLD_CONFIG and configure it."
+	exit 1
 fi
 
-RETVAL=0
+
 case "$1" in
-  start)
+    start)
 	if [ ! -d "$MYSQL_DATA_DIR/mysql" ]; then
-		nls "MySQL database not initialized. Try \"%s init\" before start." "$0" >&2
-		exit 6
+		echo "MySQL database not initialized. Try \"$0 init\" before start."
+		exit 1
 	fi
 
 	# Check if the service is already running?		
-	if [ ! -f /var/lock/subsys/mysql ]; then
+	if [ -f /var/lock/subsys/mysql ]; then
+		msg_already_running MySQL
+	else 	
 		msg_starting MySQL
 		busy
-
+		
 		if [ ! -f $MYSQLD_ERRLOG ]; then 
-			touch $MYSQLD_ERRLOG
+		    touch $MYSQLD_ERRLOG
 		fi
 		chown mysql.mysql $MYSQLD_ERRLOG
 		chmod 640 $MYSQLD_ERRLOG
@@ -91,64 +90,64 @@ case "$1" in
 		[ -z "$DEFAULT_SERVICE_RUN_NICE_LEVEL" ] && DEFAULT_SERVICE_RUN_NICE_LEVEL=0
 		TMPDIR=/tmp nice -n ${SERVICE_RUN_NICE_LEVEL:-$DEFAULT_SERVICE_RUN_NICE_LEVEL} /usr/sbin/mysqld --defaults-file=$MYSQLD_CONFIG >>$MYSQLD_ERRLOG 2>&1 &
 		sleep 1
+		deltext
 		if ps -C mysqld >/dev/null 2>&1; then
+	                RETVAL=0
 			ok
 		else
 			RETVAL=1
 			fail
 		fi
 		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/mysql
-	else 	
-		msg_already_running MySQL
 	fi
 	;;
   stop)
-	if [ -f /var/lock/subsys/mysql ]; then
-		msg_stopping MySQL
-		killproc mysqld
+        if [ -f /var/lock/subsys/mysql ]; then
+                msg_stopping MySQL
+                killproc mysqld
 		sleep 1
-		rm -f /var/lock/subsys/mysql $MYSQLD_PIDFILE >/dev/null 2>&1
-	else
-		msg_not_running MySQL
-	fi
+                rm -f /var/lock/subsys/mysql $MYSQLD_PIDFILE >/dev/null 2>&1
+        else
+                msg_not_running MySQL
+                exit 1
+        fi
 	;;
   status)
 	status mysqld
 	exit $?
 	;;
-  restart|force-reload)
+  restart|reload)
 	$0 stop
 	$0 start
-	exit $?
 	;;
   init)
 	# Check if not exist init database
 	if [ -d "$MYSQL_DATA_DIR/mysql" ]; then
-		nls "Seems that database is initialized now. Remove by hand %s" "$MYSQL_DATA_DIR/mysql"
-		nls "before initializing database."
-		exit 1;
+	    echo "Seems that database is initialized now. Remove by hand $MYSQL_DATA_DIR/mysql"
+	    echo "before initialize database."
+	    exit 1;
 	fi
 
 	show "Creating privilege mysql tables"
 	busy
 	TMP=/tmp TMPDIR=/tmp 
 	
-	# Install this in the user table, too
+	# Install this too in the user table
 	hostname="`hostname --fqdn | tr -d '[:space:]'`"
 		
 	# Check if hostname is valid
 	if [ -z "$hostname" ]; then
 		deltext
-		fail
-		nls "Sorry, the host name is not configured."
-		nls "Please configure the 'hostname' command to return a hostname."
+      		fail
+		echo "Sorry, the host name is not configured."
+		echo "Please configure the 'hostname' command to return a hostname."
 		exit 1
-	elif ! hostname -i >/dev/null 2>&1; then 
-		deltext
-		fail
-		nls "Sorry, the host '%s' could not be looked up." "$hostname"
-		nls "Please configure the 'hostname' command to return a correct hostname."
-		exit 1
+        elif ! hostname -i >/dev/null 2>&1; then 
+    		deltext
+      		fail
+      		echo "Sorry, the host '$hostname' could not be looked up."
+      		echo "Please configure the 'hostname' command to return a correct hostname."
+     		exit 1
 	fi
 
 	# Initialize variables
@@ -157,7 +156,7 @@ case "$1" in
 	c_u="" i_u=""
 	c_f="" i_f=""
 	c_t="" c_c=""
-
+	
 	# Check for old tables
 	if test ! -f $mdata/db.frm
 	then
@@ -180,11 +179,11 @@ case "$1" in
 	  c_d="$c_d KEY User (User)"
 	  c_d="$c_d )"
 	  c_d="$c_d comment='Database privileges';"
-
+	  
 	  i_d="INSERT INTO db VALUES ('%','test','','Y','Y','Y','Y','Y','Y','N','Y','Y','Y');
 	  INSERT INTO db VALUES ('%','test\_%','','Y','Y','Y','Y','Y','Y','N','Y','Y','Y');"
 	fi
-
+	
 	if test ! -f $mdata/host.frm
 	then
 	  c_h="$c_h CREATE TABLE host ("
@@ -204,7 +203,7 @@ case "$1" in
 	  c_h="$c_h )"
 	  c_h="$c_h comment='Host privileges;  Merged with database privileges';"
 	fi
-
+	
 	if test ! -f $mdata/user.frm
 	then
 	  c_u="$c_u CREATE TABLE user ("
@@ -228,7 +227,7 @@ case "$1" in
 	  c_u="$c_u   PRIMARY KEY Host (Host,User)"
 	  c_u="$c_u )"
 	  c_u="$c_u comment='Users and global privileges';"
-
+	
 	  i_u="INSERT INTO user VALUES ('localhost','mysql','','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y');
 	  INSERT INTO user VALUES ('$hostname','mysql','','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y');
 	  
@@ -237,7 +236,7 @@ case "$1" in
 	  
 	  INSERT INTO user VALUES ('localhost','mysql_logrotate','','N','N','N','N','N','N','Y','N','N','N','N','N','N','N');"
 	fi
-
+	
 	if test ! -f $mdata/func.frm
 	then
 	  c_f="$c_f CREATE TABLE func ("
@@ -249,7 +248,7 @@ case "$1" in
 	  c_f="$c_f )"
 	  c_f="$c_f   comment='User defined functions';"
 	fi
-
+	
 	if test ! -f $mdata/tables_priv.frm
 	then
 	  c_t="$c_t CREATE TABLE tables_priv ("
@@ -266,7 +265,7 @@ case "$1" in
 	  c_t="$c_t )"
 	  c_t="$c_t   comment='Table privileges';"
 	fi
-
+	
 	if test ! -f $mdata/columns_priv.frm
 	then
 	  c_c="$c_c CREATE TABLE columns_priv ("
@@ -302,6 +301,7 @@ $c_t
 $c_c
 END_OF_DATA
 	then 
+	    deltext
 	    ok
 	    cat << END_OF_MSG
 
@@ -317,6 +317,7 @@ mysqladmin section. See the manual for more instructions.
 
 END_OF_MSG
       else  
+	    deltext
 	    fail
 	    cat << END_OF_MSG
 Installation of grant tables FAILED!
@@ -351,8 +352,9 @@ END_OF_MSG
 	fi
 	;;
   *)
-	msg_usage "$0 {start|stop|init|restart|force-reload|status}"
-	exit 3
+	msg_usage "$0 {start|stop|status|restart|reload|init}"
+	exit 1
+	;;
 esac
 
 exit $RETVAL
